// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoHvrwPiBt4hPXr_BFY74Bpq0RuM-VNt8',
    appId: '1:706262091965:web:352576b9907030500a4fd4',
    messagingSenderId: '706262091965',
    projectId: 'wazir-e1d03',
    authDomain: 'wazir-e1d03.firebaseapp.com',
    storageBucket: 'wazir-e1d03.firebasestorage.app',
    measurementId: 'G-0EFT12B78Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJjx0htjnxsj-k9ShNee3NVgPoFb61Hro',
    appId: '1:706262091965:android:8bd35eb3156ae06a0a4fd4',
    messagingSenderId: '706262091965',
    projectId: 'wazir-e1d03',
    storageBucket: 'wazir-e1d03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBYQPAN6IuDOngIwBSeDhCM-NXOgE61YQ',
    appId: '1:706262091965:ios:70413ac06ec924660a4fd4',
    messagingSenderId: '706262091965',
    projectId: 'wazir-e1d03',
    storageBucket: 'wazir-e1d03.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBYQPAN6IuDOngIwBSeDhCM-NXOgE61YQ',
    appId: '1:706262091965:ios:70413ac06ec924660a4fd4',
    messagingSenderId: '706262091965',
    projectId: 'wazir-e1d03',
    storageBucket: 'wazir-e1d03.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoHvrwPiBt4hPXr_BFY74Bpq0RuM-VNt8',
    appId: '1:706262091965:web:8f10810e935d153b0a4fd4',
    messagingSenderId: '706262091965',
    projectId: 'wazir-e1d03',
    authDomain: 'wazir-e1d03.firebaseapp.com',
    storageBucket: 'wazir-e1d03.firebasestorage.app',
    measurementId: 'G-SVKFZYDEH2',
  );
}
